import { Issue, Member, Project, Sprint } from "@/lib/types";

export const members: Member[] = [
  { id: "m1", name: "John Carter", initials: "JC", avatar: "https://i.pravatar.cc/150?img=1", role: "Frontend Dev" },
  { id: "m2", name: "Sarah Lee", initials: "SL", avatar: "https://i.pravatar.cc/150?img=5", role: "Backend Dev" },
  { id: "m3", name: "David Smith", initials: "DS", avatar: "https://i.pravatar.cc/150?img=8", role: "Designer" },
  { id: "m4", name: "Emma Wilson", initials: "EW", avatar: "https://i.pravatar.cc/150?img=9", role: "QA Engineer" },
  { id: "m5", name: "Alex Brown", initials: "AB", avatar: "https://i.pravatar.cc/150?img=12", role: "DevOps" },
  { id: "m6", name: "Olivia Taylor", initials: "OT", avatar: "https://i.pravatar.cc/150?img=20", role: "PM" },
];

export const projects: Project[] = [
  {
    id: "ph",
    key: "PH",
    code: "PH-4821",
    name: "Phoenix App",
    description: "Mobile-first rewrite of the customer app with React Native",
    color: "avatar-orb-amber",
    members: [members[0], members[1], members[2], members[3]],
    openIssues: 24,
    totalIssues: 80,
    progress: 62,
    updatedAt: "2026-06-08",
    status: "active",
  },
  {
    id: "or",
    key: "OR",
    code: "OR-7293",
    name: "Orion Backend",
    description: "Microservices migration from monolith, targeting Go & gRPC",
    color: "avatar-orb-blue",
    members: [members[1], members[4], members[5]],
    openIssues: 17,
    totalIssues: 55,
    progress: 45,
    updatedAt: "2026-06-07",
    status: "active",
  },
  {
    id: "we",
    key: "WE",
    code: "WE-1156",
    name: "Web Redesign",
    description: "Complete visual overhaul of the marketing site and docs",
    color: "avatar-orb-violet",
    members: [members[2], members[3], members[0]],
    openIssues: 9,
    totalIssues: 30,
    progress: 80,
    updatedAt: "2026-06-06",
    status: "active",
  },
  {
    id: "ad",
    key: "AD",
    code: "AD-6047",
    name: "App Development",
    description: "Internal tooling and admin panel for operations team",
    color: "avatar-orb-emerald",
    members: [members[0], members[5]],
    openIssues: 31,
    totalIssues: 60,
    progress: 30,
    updatedAt: "2026-06-05",
    status: "active",
  },
  {
    id: "rd",
    key: "RD",
    code: "RD-3318",
    name: "Responsive Design",
    description: "Audit and fix responsive breakpoints across all web properties",
    color: "avatar-orb-pink",
    members: [members[2], members[3]],
    openIssues: 5,
    totalIssues: 20,
    progress: 90,
    updatedAt: "2026-06-03",
    status: "active",
  },
];

export const sprints: Sprint[] = [
  { id: "s1", projectId: "ph", name: "Sprint 8", goal: "Ship auth refactor & onboarding flow", startDate: "2026-06-02", endDate: "2026-06-13", status: "active" },
  { id: "s2", projectId: "or", name: "Sprint 5", goal: "gRPC gateway & user service migration", startDate: "2026-06-02", endDate: "2026-06-13", status: "active" },
];

export const issues: Issue[] = [
  {
    id: "i1", code: "PH-001", title: "Login page is not responsive", type: "Bug",
    status: "In Progress", priority: "High", projectId: "ph", sprintId: "s1",
    assignees: [members[0], members[1]], reporter: members[5],
    storyPoints: 3, dueDate: "2026-06-12",
    createdAt: "2026-06-01", updatedAt: "2026-06-08",
  },
  {
    id: "i2", code: "PH-002", title: "Add biometric auth option to login", type: "Story",
    status: "Todo", priority: "Medium", projectId: "ph", sprintId: "s1",
    assignees: [members[0]], reporter: members[5],
    storyPoints: 5, dueDate: "2026-06-13",
    createdAt: "2026-06-01", updatedAt: "2026-06-07",
  },
  {
    id: "i3", code: "PH-003", title: "Onboarding carousel crashes on Android 13", type: "Bug",
    status: "In Progress", priority: "Critical", projectId: "ph", sprintId: "s1",
    assignees: [members[1], members[3]], reporter: members[3],
    storyPoints: 8, dueDate: "2026-06-10",
    createdAt: "2026-06-02", updatedAt: "2026-06-08",
  },
  {
    id: "i4", code: "PH-004", title: "Profile image upload — resize before upload", type: "Task",
    status: "Reviewing", priority: "Low", projectId: "ph", sprintId: "s1",
    assignees: [members[2]], reporter: members[0],
    storyPoints: 2,
    createdAt: "2026-06-03", updatedAt: "2026-06-08",
  },
  {
    id: "i5", code: "PH-005", title: "Push notification opt-in screen", type: "Story",
    status: "In Progress", priority: "Medium", projectId: "ph", sprintId: "s1",
    assignees: [members[0], members[3]], reporter: members[5],
    storyPoints: 3,
    createdAt: "2026-06-03", updatedAt: "2026-06-09",
  },
  {
    id: "i6", code: "PH-006", title: "Dark mode: tab bar icons incorrect tint", type: "Bug",
    status: "Completed", priority: "Low", projectId: "ph", sprintId: "s1",
    assignees: [members[2]], reporter: members[2],
    storyPoints: 1,
    createdAt: "2026-06-04", updatedAt: "2026-06-08",
  },
  {
    id: "i7", code: "PH-007", title: "Design system tokens — typography scale", type: "Task",
    status: "Completed", priority: "Medium", projectId: "ph", sprintId: "s1",
    assignees: [members[2]], reporter: members[5],
    storyPoints: 2,
    createdAt: "2026-06-04", updatedAt: "2026-06-07",
  },
  {
    id: "i8", code: "OR-001", title: "Set up gRPC gateway service", type: "Epic",
    status: "In Progress", priority: "High", projectId: "or", sprintId: "s2",
    assignees: [members[1], members[4]], reporter: members[5],
    storyPoints: 13,
    createdAt: "2026-06-02", updatedAt: "2026-06-08",
  },
  {
    id: "i9", code: "OR-002", title: "Migrate user service to Go", type: "Story",
    status: "Todo", priority: "High", projectId: "or", sprintId: "s2",
    assignees: [members[1]], reporter: members[5],
    storyPoints: 8,
    createdAt: "2026-06-02", updatedAt: "2026-06-06",
  },
  {
    id: "i10", code: "OR-003", title: "Write integration tests for auth endpoints", type: "Task",
    status: "Reviewing", priority: "Medium", projectId: "or", sprintId: "s2",
    assignees: [members[3]], reporter: members[1],
    storyPoints: 5,
    createdAt: "2026-06-03", updatedAt: "2026-06-09",
  },
  {
    id: "i11", code: "OR-004", title: "Kanban drag and drop not persisting", type: "Bug",
    status: "In Progress", priority: "Critical", projectId: "or",
    assignees: [members[1], members[4]], reporter: members[4],
    storyPoints: 3,
    createdAt: "2026-06-05", updatedAt: "2026-06-08",
  },
];
